"""Render the human-readable README.md cover document.

Pure f-string templating — no Jinja dependency. The receiver reads this first.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional


def render_readme(
    *,
    # Case
    case_reference:       str,
    requesting_authority: str,
    legal_basis:          str,
    retention_until:      Optional[datetime],
    # Incident
    incident_ref:         Optional[str],
    incident_title:       str,
    incident_id:          str,
    severity:             str,
    tlp:                  str,
    phase:                str,
    status:               str,
    occurred_at_utc:      Optional[str],
    detected_at_utc:      Optional[str],
    contained_at_utc:     Optional[str],
    eradicated_at_utc:    Optional[str],
    recovered_at_utc:     Optional[str],
    # Generation
    generated_at_utc:     str,
    generator_username:   str,
    generator_role:       str,
    generator_user_id:    str,
    platform_version:     str,
    bundle_sha256:        str,
    manifest_sha256:      str,
    hmac_sha256:          str,
    audit_anchor_row_id:  str,
    audit_anchor_row_hash: str,
    trusted_timestamp:    Optional[dict],   # {time, tsa} when MANIFEST.tst was written, else None
    # Build options (truth in advertising — record what was filtered)
    legal_hold_only:      bool,
    include_artifacts:    bool,
    # Counts
    file_count:           int,
    total_bytes:          int,
    evidence_count:       int,
    audit_row_count:      int,
) -> str:
    legal_basis_label = {
        "warrant":      "Warrant",
        "subpoena":     "Subpoena",
        "court_order":  "Court order",
        "mla":          "Mutual Legal Assistance Treaty (MLAT)",
        "voluntary":    "Voluntary disclosure",
        "other":        "Other (see CASE_INFO.json)",
    }.get(legal_basis, legal_basis)

    if retention_until is not None:
        ru = retention_until if retention_until.tzinfo else retention_until.replace(tzinfo=timezone.utc)
        retention_line = (f"**Retention until:**      "
                          f"{ru.astimezone(timezone.utc).isoformat().replace('+00:00', 'Z')}")
    else:
        retention_line = "**Retention until:**      indefinite (no expiry recorded)"

    if trusted_timestamp:
        tst_line = (f"- **Trusted timestamp:**  `MANIFEST.tst`: RFC 3161 token over SHA-256(MANIFEST.json) from "
                    f"{trusted_timestamp.get('tsa') or 'the configured TSA'}, time {trusted_timestamp.get('time') or 'see token'}")
        tst_layout = "    MANIFEST.tst                        RFC 3161 time-stamp token over SHA-256(MANIFEST.json) (DER)\n"
        tst_verify = """
5. Verify the trusted timestamp independently of this platform's clock:

       openssl ts -verify -data MANIFEST.json -in MANIFEST.tst -CAfile <TSA CA certificate>
"""
    else:
        tst_line = ("- **Trusted timestamp:**  none: no `MANIFEST.tst` (no time-stamping authority was configured, "
                    "or it did not answer at generation); times come from the platform clock only")
        tst_layout = ""
        tst_verify = ""

    filter_notes = []
    if legal_hold_only:
        filter_notes.append("Only Evidence items flagged `legal_hold = true` were included.")
    if not include_artifacts:
        filter_notes.append("Quarantine artifacts (`05_Artifacts/`) were **NOT** included — opt-in at generation only.")
    filter_block = ("\n".join(f"  - {n}" for n in filter_notes)) if filter_notes else "  - All evidence and all artifacts included."

    return f"""\
# DFIR-FENRIR — Law Enforcement Evidence Package

**Case Reference:**       {case_reference}
**Requesting Authority:** {requesting_authority}
**Legal Basis:**          {legal_basis_label}
{retention_line}
**Classification:**       TLP:{tlp.upper()}

## Source Incident

- **Reference:**       {incident_ref or "(unnumbered)"}
- **Title:**           {incident_title}
- **Incident ID:**     {incident_id}
- **Severity:**        {severity}    (internal scale: low | medium | high | critical)
- **Phase at export:** {phase}       (NIST SP 800-61 R3)
- **Status:**          {status}
- **Occurred at (UTC):**   {occurred_at_utc or "—"}
- **Detected at (UTC):**   {detected_at_utc or "—"}
- **Contained at (UTC):**  {contained_at_utc or "—"}
- **Eradicated at (UTC):** {eradicated_at_utc or "—"}
- **Recovered at (UTC):**  {recovered_at_utc or "—"}

## Generation

- **Generated (UTC):**    {generated_at_utc}
- **Generated by:**       {generator_username} ({generator_role}) — user-id {generator_user_id}
- **Platform:**           DFIR-FENRIR {platform_version}
- **Bundle SHA-256:**     {bundle_sha256}
- **Manifest SHA-256:**   {manifest_sha256}
- **HMAC-SHA-256 sig:**   {hmac_sha256}  *(key = SHA-256(bundle password))*
- **Audit anchor row:**   {audit_anchor_row_id}
- **Audit anchor hash:**  {audit_anchor_row_hash}
- **Time source:**        container clock (NTP-disciplined host); recorded UTC
{tst_line}

## What this package contains

- **Files in manifest:**  {file_count:,}
- **Content size:**       {total_bytes:,} bytes (the files listed in MANIFEST.json, uncompressed, before encryption)
- **Evidence items:**     {evidence_count:,}
- **Audit rows:**         {audit_row_count:,}

### Build filters applied

{filter_block}

## Package layout

    README.md                           This file
    CASE_INFO.json                      Structured case metadata
    MANIFEST.json                       Machine-readable file manifest (SHA-256, SHA-512, size, MIME, source)
    MANIFEST.txt                        Human-readable equivalent of MANIFEST.json
    INTEGRITY.sha256                    `sha256sum --check INTEGRITY.sha256` compatible
    INTEGRITY.sig                       HMAC-SHA-256 of MANIFEST.json, key = SHA-256(bundle password) (hex)
{tst_layout}
    01_Incident/                        Incident summary, closure checklist, lessons learned (JSON)
    02_Timeline/                        Chronological event log (CSV + JSON)
    03_IOCs/                            Indicators of Compromise (CSV + JSON)
    04_Evidence/                        Evidence inventory, per-item custody logs, decrypted files
    05_Artifacts/                       Quarantine + suspected malware (only present if opt-in was set)
    06_Forensic/                        PCAP analyses (JSON), YARA matches (CSV)
    07_Communications/                  Comments, OOB log, stakeholders
    08_Audit/                           This incident's audit-log rows (hash-chained) + per-row verifier output
    09_Legal/                           Chain-of-custody SOP + tool provenance + TLP handling
    10_Case_Notes/                      Append-only case notes (CSV), each with its content SHA-256 (present if any).
                                        Recompute: SHA-256 of UTF-8 JSON, keys sorted, separators "," ":",
                                        {{v:1, id, incident_id, author_id, created_at (as in the CSV), body,
                                        corrects_id, source_scratchpad_id (null if empty), evidence_ids,
                                        entity_ids, ioc_ids, timeline_event_ids (sorted lists)}}
    11_Recovery/                        Recovery tracker (CSV): per compromised system, the restore point, who restored
                                        and validated it and when, the validation method and the monitoring window
                                        (present if any).
    12_Notifications/                   Stakeholder notification tracker (CSV): per stakeholder-matrix obligation, when its
                                        countdown started and was due, and who notified the stakeholder, when and how,
                                        or why it was not required (present if any).
    13_Sign_Offs/                       Phase-gate sign-offs (CSV): the Incident Commander's and the DPO's, who signed which
                                        gate, on what basis and when, the statement and the SHA-256 of the gate state
                                        they signed; "current" = made since the last re-open (present if any).

## How to open this package

The archive you received is a standard **AES-256 password-protected ZIP**
(WinZip AE-2). Open it with any modern archive tool:

  - macOS:   double-click → enter password
  - Windows: 7-Zip / WinRAR → enter password
  - Linux:   `unzip -P <password> bundle.zip`

The password was delivered out of band; verify its first/last 4 characters
match the `key_hint` in the transfer message before using it.

After unzipping the outer envelope you will find `le_package.zip` — the
inner evidence archive containing the directory structure documented below.
The inner archive is **not** itself encrypted: the outer envelope protects
it. Only `05_Artifacts/Files.zip` (present when artifacts were included) is
password-protected, with the password `infected` (the standard
malware-analyst convention, so antivirus cannot auto-execute its contents
during extraction).

## How this package was extracted

DFIR-FENRIR's LE-package builder read this incident's records with ordinary
database queries in one session (PostgreSQL READ COMMITTED: not a single
snapshot and not a read-only transaction, so a record changed while the
package was being built can appear in one file and not in another; the
generation time above bounds when the reads happened). Files in
`04_Evidence/Files/` were decrypted from their at-rest AES-256-GCM
ciphertext — a file stored since 2026-10-04 under its own random data key,
which the platform unwraps (AES-KW) with a key derived from its master
evidence key (KEK) by HKDF-SHA256; an older file directly under the KEK —
and placed into the inner evidence ZIP, which the outer AES-256 ZIP protects
under the password shown once at generation. No key used at rest is in this
package. Each file was authenticated in full before it was written; one that
failed is listed in its `.meta.json` as not included (`integrity_failed:` =
tampered or corrupt, and the platform froze it). Exhibits whose chain of
custody was not sealed are left out unless the sender included them
(`CASE_INFO.json` build_options; `Evidence_Inventory.csv` package_inclusion).

The SHA-256 of every file was computed in memory over the exact bytes
written and recorded in `MANIFEST.json`. After the package was sealed, the
platform wrote a `le_package_generate` row to its hash-chained audit log
carrying the Manifest SHA-256, the bundle SHA-256 and the HMAC above.
Because that row is written after the build, it is **not** in this
package's `08_Audit/` and `MANIFEST.json` carries no anchor: its id and
`row_hash` are kept on the platform's record of this package (the
**Audit anchor** lines above point there) and can be obtained from the
sender. Tampering with any file in the package fails SHA-256 verification.

## How to verify integrity

1. From the bundle root:

       sha256sum --check INTEGRITY.sha256

   Every entry must report `OK`. A single mismatch invalidates the bundle.

2. Confirm the manifest itself:

       sha256sum MANIFEST.json

   It must match the **Manifest SHA-256** above (the platform also recorded
   it in its `le_package_generate` audit row after the build; see above).

3. Check the included audit rows:

       cat 08_Audit/Hash_Chain_Verification.txt   # last line: RESULT: VERIFIED ✓

   The verifier recomputes each included row's `row_hash` from that row's
   content and its stored `prev_hash`. The rows are this incident's subset
   of the platform-wide chain, so the links between them are not checked
   here, and this package's own `le_package_generate` row is not among them.

4. Verify the HMAC sender-of-record signature. The HMAC key is derived
   deterministically from the bundle password — so anyone who can open
   the ZIP can also verify the HMAC:

       python3 -c "import hashlib,hmac,sys; \\
         pw  = sys.argv[1].encode('utf-8'); \\
         key = hashlib.sha256(pw).digest(); \\
         mf  = open(sys.argv[2],'rb').read(); \\
         print(hmac.new(key, mf, hashlib.sha256).hexdigest())" \\
         '<bundle-password>' MANIFEST.json

   The output must equal the contents of `INTEGRITY.sig` (and the
   **HMAC-SHA-256 sig** value above).
{tst_verify}
## Chain-of-custody declaration

This package was generated under controlled conditions and aligns with:

  - NIST SP 800-86 — Guide to Integrating Forensic Techniques into IR
  - ISO/IEC 27037   — Digital evidence: identification, collection, acquisition,
                       preservation
  - ACPO Good Practice Guide for Digital Evidence (UK)
  - SWGDE Best Practices for Digital Evidence

The full SOP — what each of those means concretely for this platform — is at
`09_Legal/Chain_of_Custody_SOP.md`. Platform build and crypto provenance is
at `09_Legal/Tool_Provenance.json`.

## Receiving-party acknowledgement

  Name (printed):  ____________________________________________
  Title / Agency:  ____________________________________________
  Received (UTC):  ____________________________________________
  Signature:       ____________________________________________

## Distribution

This package is classified **TLP:{tlp.upper()}**. Distribute strictly per
TLP 2.0 rules. Unauthorised disclosure may compromise the investigation, the
victim, or third parties. See `09_Legal/TLP_Statement.md` for handling guidance.

— END —
"""
