"""Render the human-readable README.md cover document.

Pure f-string templating — no Jinja dependency. The receiver reads this first.
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional


def render_readme(
    *,
    # Case
    case_reference:       str,
    requesting_authority: str,
    legal_basis:          str,
    retention_until:      Optional[datetime],
    # Incident
    incident_ref:         Optional[str],
    incident_title:       str,
    incident_id:          str,
    severity:             str,
    tlp:                  str,
    phase:                str,
    status:               str,
    occurred_at_utc:      Optional[str],
    contained_at_utc:     Optional[str],
    # Generation
    generated_at_utc:     str,
    generator_username:   str,
    generator_role:       str,
    generator_user_id:    str,
    platform_version:     str,
    bundle_sha256:        str,
    manifest_sha256:      str,
    hmac_sha256:          str,
    audit_anchor_row_id:  str,
    audit_anchor_row_hash: str,
    # Build options (truth in advertising — record what was filtered)
    legal_hold_only:      bool,
    include_artifacts:    bool,
    # Counts
    file_count:           int,
    total_bytes:          int,
    evidence_count:       int,
    audit_row_count:      int,
) -> str:
    legal_basis_label = {
        "warrant":      "Warrant",
        "subpoena":     "Subpoena",
        "court_order":  "Court order",
        "mla":          "Mutual Legal Assistance Treaty (MLAT)",
        "voluntary":    "Voluntary disclosure",
        "other":        "Other (see CASE_INFO.json)",
    }.get(legal_basis, legal_basis)

    retention_line = (
        f"**Retention until:**      {retention_until.replace(microsecond=0).isoformat()}Z"
        if retention_until else
        "**Retention until:**      indefinite (no expiry recorded)"
    )

    filter_notes = []
    if legal_hold_only:
        filter_notes.append("Only Evidence items flagged `legal_hold = true` were included.")
    if not include_artifacts:
        filter_notes.append("Quarantine artifacts (`05_Artifacts/`) were **NOT** included — opt-in at generation only.")
    filter_block = ("\n".join(f"  - {n}" for n in filter_notes)) if filter_notes else "  - All evidence and all artifacts included."

    return f"""\
# DFIR-FENRIR — Law Enforcement Evidence Package

**Case Reference:**       {case_reference}
**Requesting Authority:** {requesting_authority}
**Legal Basis:**          {legal_basis_label}
{retention_line}
**Classification:**       TLP:{tlp.upper()}

## Source Incident

- **Reference:**       {incident_ref or "(unnumbered)"}
- **Title:**           {incident_title}
- **Incident ID:**     {incident_id}
- **Severity:**        {severity}    (internal scale: low | medium | high | critical)
- **Phase at export:** {phase}       (NIST SP 800-61 R3)
- **Status:**          {status}
- **Occurred at (UTC):**   {occurred_at_utc or "—"}
- **Contained at (UTC):**  {contained_at_utc or "—"}

## Generation

- **Generated (UTC):**    {generated_at_utc}
- **Generated by:**       {generator_username} ({generator_role}) — user-id {generator_user_id}
- **Platform:**           DFIR-FENRIR {platform_version}
- **Bundle SHA-256:**     {bundle_sha256}
- **Manifest SHA-256:**   {manifest_sha256}
- **HMAC-SHA-256 sig:**   {hmac_sha256}  *(key = SHA-256(bundle password))*
- **Audit anchor row:**   {audit_anchor_row_id}
- **Audit anchor hash:**  {audit_anchor_row_hash}
- **Time source:**        container clock (NTP-disciplined host); recorded UTC

## What this package contains

- **Files in bundle:**    {file_count:,}
- **Bundle size:**        {total_bytes:,} bytes (encrypted)
- **Evidence items:**     {evidence_count:,}
- **Audit rows:**         {audit_row_count:,}

### Build filters applied

{filter_block}

## Package layout

    README.md                           This file
    CASE_INFO.json                      Structured case metadata
    MANIFEST.json                       Machine-readable file manifest (SHA-256, SHA-512, size, MIME, source)
    MANIFEST.txt                        Human-readable equivalent of MANIFEST.json
    INTEGRITY.sha256                    `sha256sum --check INTEGRITY.sha256` compatible
    INTEGRITY.sig                       HMAC-SHA-256 of MANIFEST.json under bundle KEK (hex)

    01_Incident/                        Incident metadata (JSON + HTML narrative)
    02_Timeline/                        Chronological event log (CSV + JSON)
    03_IOCs/                            Indicators of Compromise (CSV + JSON)
    04_Evidence/                        Evidence inventory, per-item custody logs, decrypted files
    05_Artifacts/                       Quarantine + suspected malware (only present if opt-in was set)
    06_Forensic/                        PCAP, YARA, detections
    07_Communications/                  Comments, OOB log, stakeholders
    08_Audit/                           Full tamper-evident audit trail + chain-verifier output
    09_Legal/                           Chain-of-custody SOP + tool provenance + TLP handling

## How to open this package

The archive you received is a standard **AES-256 password-protected ZIP**
(WinZip AE-2). Open it with any modern archive tool:

  - macOS:   double-click → enter password
  - Windows: 7-Zip / WinRAR → enter password
  - Linux:   `unzip -P <password> bundle.zip`

The password was delivered out of band; verify its first/last 4 characters
match the `key_hint` in the transfer message before using it.

After unzipping the outer envelope you will find `le_package.zip` — the
inner evidence archive containing the directory structure documented below.
That inner archive is itself a password-protected ZIP (password: `infected`,
the standard malware-analyst convention, set so antivirus cannot
auto-execute its contents during extraction).

## How this package was extracted

This package was produced by DFIR-FENRIR's LE-package builder under a single
read-only database transaction. Files in `04_Evidence/Files/` were decrypted
from their at-rest AES-256-GCM ciphertext using ephemeral KEKs derived from
the platform's master KEK, then placed into the inner evidence ZIP. The
inner ZIP and the platform-side audit anchor are protected by the outer
AES-256 ZIP whose password was shown once at generation.

SHA-256 of every file was computed in-memory immediately before write and
recorded in `MANIFEST.json`. The manifest itself was hashed and the resulting
fingerprint was written to a `le_package_generate` row of the platform's
hash-chained audit log — that row's `row_hash` is the **Audit anchor hash**
above. Tampering with any file in the package will fail SHA-256 verification;
tampering with the audit chain is detectable independently.

## How to verify integrity

1. From the bundle root:

       sha256sum --check INTEGRITY.sha256

   Every entry must report `OK`. A single mismatch invalidates the bundle.

2. Confirm the manifest itself:

       sha256sum MANIFEST.json

   It must match the **Manifest SHA-256** above (which is anchored in the
   audit chain at the row referenced by **Audit anchor row** above).

3. Confirm the audit chain (an audit row in `08_Audit/Audit_Trail.csv` has
   `action = le_package_generate` and `row_hash` equal to the anchor above;
   the chain verifier output below confirms the rest of the chain is intact):

       cat 08_Audit/Hash_Chain_Verification.txt   # last line: VERIFIED ✓

4. Verify the HMAC sender-of-record signature. The HMAC key is derived
   deterministically from the bundle password — so anyone who can open
   the ZIP can also verify the HMAC:

       python3 -c "import hashlib,hmac,sys; \\
         pw  = sys.argv[1].encode('utf-8'); \\
         key = hashlib.sha256(pw).digest(); \\
         mf  = open(sys.argv[2],'rb').read(); \\
         print(hmac.new(key, mf, hashlib.sha256).hexdigest())" \\
         '<bundle-password>' MANIFEST.json

   The output must equal the contents of `INTEGRITY.sig` (and the
   **HMAC-SHA-256 sig** value above).

## Chain-of-custody declaration

This package was generated under controlled conditions and aligns with:

  - NIST SP 800-86 — Guide to Integrating Forensic Techniques into IR
  - ISO/IEC 27037   — Digital evidence: identification, collection, acquisition,
                       preservation
  - ACPO Good Practice Guide for Digital Evidence (UK)
  - SWGDE Best Practices for Digital Evidence

The full SOP — what each of those means concretely for this platform — is at
`09_Legal/Chain_of_Custody_SOP.md`. Platform build and crypto provenance is
at `09_Legal/Tool_Provenance.json`.

## Receiving-party acknowledgement

  Name (printed):  ____________________________________________
  Title / Agency:  ____________________________________________
  Received (UTC):  ____________________________________________
  Signature:       ____________________________________________

## Distribution

This package is classified **TLP:{tlp.upper()}**. Distribute strictly per
TLP 2.0 rules. Unauthorised disclosure may compromise the investigation, the
victim, or third parties. See `09_Legal/TLP_Statement.md` for handling guidance.

— END —
"""
