#!/usr/bin/env bash
# DFIR-FENRIR v2 — regenerate the hash-pinned Python lockfiles (supply chain).
#
#   backend/requirements.lock          ← backend/requirements.txt + constraints.txt
#   analysis-worker/requirements.lock  ← analysis-worker/requirements.txt
#
# The Dockerfiles install with `pip --require-hashes -r requirements.lock`, so a
# build fails if any downloaded artifact differs from what was locked here.
# The project's 14-day cooldown rule is enforced by uv's --exclude-newer: nothing
# released in the last 14 days (or after CUTOFF) can enter a lockfile.
#
# Run after editing requirements.txt / constraints.txt (`make lock`). Needs network
# (it resolves against PyPI); builds do not need to re-run it. Idempotent: the same
# inputs + cutoff always produce the same files.
#   scripts/lock-python.sh               # cutoff = today − 14 days (UTC)
#   CUTOFF=2026-09-16 scripts/lock-python.sh
set -euo pipefail
cd "$(dirname "$0")/.."

CUTOFF="${CUTOFF:-$(date -u -d '14 days ago' +%Y-%m-%d)}"
UV_VERSION=0.12.15            # itself released before the cooldown cutoff it enforces
PY_IMAGE="$(sed -n 's/^FROM \(python:3\.12-slim@sha256:[0-9a-f]*\).*/\1/p' backend/Dockerfile | head -1)"
PY_IMAGE="${PY_IMAGE:-python:3.12-slim}"

echo "Locking with uv $UV_VERSION in $PY_IMAGE — excluding releases after $CUTOFF"
docker run --rm -u "$(id -u):$(id -g)" -e HOME=/tmp -e CUTOFF="$CUTOFF" \
    -v "$PWD:/w" -w /w "$PY_IMAGE" sh -euc "
        pip install --quiet --no-cache-dir --target /tmp/uv uv==$UV_VERSION
        UV='python -m uv' ; export PYTHONPATH=/tmp/uv
        common='--generate-hashes --universal --python-version 3.12 --exclude-newer ${CUTOFF}T00:00:00Z --no-header --quiet'
        \$UV pip compile backend/requirements.txt -c backend/constraints.txt \$common -o backend/requirements.lock
        \$UV pip compile analysis-worker/requirements.txt \$common -o analysis-worker/requirements.lock
    "
for f in backend/requirements.lock analysis-worker/requirements.lock; do
    sed -i "1i # GENERATED by scripts/lock-python.sh (cutoff $CUTOFF) — do not edit; edit requirements.txt and re-run." "$f"
    printf '%-36s %3d packages, %4d hashes\n' "$f" "$(grep -cE '^[a-zA-Z0-9]' "$f")" "$(grep -c -- '--hash=' "$f")"
done
