// Custody-log vocabulary: one label and colour per audited evidence action, shared by Evidence ›
// Custody log and the item detail's custody timeline (G-fix FE-L8: one copy). An action missing here
// shows its raw name.

export const CUSTODY_ACTION_COLOR = {
  evidence_collect:                  'var(--ok)',
  evidence_collect_rejected:         'var(--crit)',
  evidence_acquisition_record:       'var(--accent)',
  evidence_acquisition_record_rejected: 'var(--crit)',
  evidence_seal:                     'var(--accent)',
  email_mint_evidence:               'var(--ok)',
  webhistory_mint_evidence:          'var(--ok)',
  evidence_update:                   'var(--muted)',
  evidence_photo_add:                'var(--muted)',
  evidence_transfer_request:         'var(--med)',
  evidence_transfer:                 'var(--accent)',
  evidence_transfer_declined:        'var(--high)',
  evidence_examine:                  'var(--med)',
  evidence_verify:                   'var(--ok)',
  evidence_verify_failed:            'var(--crit)',
  evidence_read_failed:              'var(--high)',
  evidence_kek_id_mismatch:          'var(--high)',
  file_read_failed:                  'var(--high)',
  forensic_import_rejected:          'var(--crit)',
  evidence_destroy:                  'var(--crit)',
  evidence_return:                   'var(--high)',
  evidence_archive:                  'var(--muted)',
  evidence_mirror_purged:            'var(--muted)',
  evidence_storage_rekeyed:          'var(--muted)',
  evidence_export:                   'var(--accent)',
  evidence_export_create:            'var(--accent)',
  evidence_export_download:          'var(--accent)',
  evidence_export_download_denied:   'var(--crit)',
  evidence_amend_after_seal:         'var(--high)',
  evidence_copy_mint:                'var(--accent)',
  evidence_copy_correction:          'var(--high)',
  evidence_working_copy_issued:      'var(--accent)',
  evidence_working_copy_complete:    'var(--ok)',
  evidence_working_copy_aborted:     'var(--high)',
  evidence_working_copy_failed:      'var(--crit)',
  evidence_working_copy_recorded:    'var(--accent)',
  evidence_working_copy_verify:      'var(--ok)',
  evidence_working_copy_verify_failed: 'var(--crit)',
  evidence_legal_hold_set:           'var(--med)',
  evidence_legal_hold_released:      'var(--muted)',
}

export const CUSTODY_ACTION_LABEL = {
  evidence_collect:                'Collected',
  evidence_collect_rejected:       'Collection REFUSED',
  evidence_acquisition_record:     'Acquisition record',
  evidence_acquisition_record_rejected: 'Acquisition record REFUSED',
  evidence_seal:                   'Sealed',
  email_mint_evidence:             'Collected (from Email)',
  webhistory_mint_evidence:        'Collected (from Browser history)',
  evidence_update:                 'Updated',
  evidence_photo_add:              'Photo added',
  evidence_transfer_request:       'Transfer requested',
  evidence_transfer:               'Transferred',
  evidence_transfer_declined:      'Transfer declined',
  evidence_examine:                'Examined',
  evidence_verify:                 'Verified',
  evidence_verify_failed:          'Verify FAILED',
  evidence_read_failed:            'Stored file could not be read',
  evidence_kek_id_mismatch:        'Stored file names another key (KEK id)',
  file_read_failed:                'Stored file could not be read',
  forensic_import_rejected:        'Import REFUSED (hash mismatch)',
  evidence_destroy:                'Destroyed',
  evidence_return:                 'Returned',
  evidence_archive:                'Archived',
  evidence_mirror_purged:          'Backup mirror copy purged',
  evidence_storage_rekeyed:        'Storage key rotated (KEK rotation)',
  evidence_export:                 'Exported',
  evidence_export_create:          'Export bundle created',
  evidence_export_download:        'Export downloaded',
  evidence_export_download_denied: 'Export download denied',
  evidence_amend_after_seal:       'Amended after seal',
  evidence_copy_mint:              'Export copy recorded',
  evidence_copy_correction:        'Working copy correction',
  evidence_working_copy_issued:    'Working copy issued',
  evidence_working_copy_complete:  'Working copy downloaded',
  evidence_working_copy_aborted:   'Working copy download aborted',
  evidence_working_copy_failed:    'Working copy FAILED integrity',
  evidence_working_copy_recorded:  'Lab copy recorded',
  evidence_working_copy_verify:    'Working copy verified',
  evidence_working_copy_verify_failed: 'Working copy changed',
  evidence_legal_hold_set:         'Legal hold set',
  evidence_legal_hold_released:    'Legal hold released',
}
